package com.gm.ofi.orm.mybatis.model;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userid
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userid
     *
     * @return the value of users.userid
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userid
     *
     * @param userid the value for users.userid
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Fri Aug 09 11:35:17 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}